#!/usr/bin/env bash
# Build MBD-Videoconverter for macOS arm64, macOS x64, Windows amd64.
#
# Requires:
#   macOS arm64:  Go 1.21+, Xcode CLT
#   macOS x64 + Windows: Docker + fyne-cross
#     go install github.com/fyne-io/fyne-cross@latest
#     go install fyne.io/fyne/v2/cmd/fyne@latest

set -euo pipefail
export PATH="$HOME/go/bin:$PATH"

# Clean up any generated version file on exit (covers normal exit and errors)
trap 'rm -f internal/version/version_gen.go' EXIT

# ── Version bump (auto-increment patch) ──────────────────────────────────────
VFILE=VERSION
CURRENT=$(cat "$VFILE")
MAJORMINOR=${CURRENT%.*}
PATCH=${CURRENT##*.}
NEXT="${MAJORMINOR}.$((PATCH + 1))"
echo "$NEXT" > "$VFILE"
VERSION=$NEXT
echo "Version: $VERSION"

LDFLAGS="-s -w -X github.com/webfraggle/mbd-video-converter/internal/version.Version=$VERSION"
APPID="de.modellbahn-displays.mbd-videoconverter"
OUTDIR="dist"
mkdir -p "$OUTDIR"

# fyne-cross splits -ldflags on spaces (strings.Fields), which breaks -X importpath=value.
# Work around: write a generated Go file with the version baked in, use it for fyne-cross
# builds (which run inside Docker / local fyne tool), then remove it afterwards.
VERSION_GEN="internal/version/version_gen.go"
fyne_cross_version_inject() {
  cat > "$VERSION_GEN" <<GOEOF
// Code generated by build.sh — DO NOT EDIT.
package version

func init() { Version = "$VERSION" }
GOEOF
}
fyne_cross_version_clean() {
  rm -f "$VERSION_GEN"
}

# ── Locate or download ffmpeg per platform ───────────────────────────────────
# These URLs need updating to current evermeet/BtbN releases. Replace placeholders.
FFMPEG_DARWIN_ARM64="${FFMPEG_DARWIN_ARM64:-/opt/homebrew/bin/ffmpeg}"
FFMPEG_DARWIN_X64="${FFMPEG_DARWIN_X64:-/usr/local/bin/ffmpeg}"
FFMPEG_WIN_AMD64="${FFMPEG_WIN_AMD64:-./build-deps/ffmpeg.exe}"

# ── macOS arm64 (native) ─────────────────────────────────────────────────────
echo "Building macOS arm64..."
ARM_BUNDLE="$OUTDIR/macos-arm64/MBD-Videoconverter.app"
rm -rf "$ARM_BUNDLE"
mkdir -p "$ARM_BUNDLE/Contents/MacOS" "$ARM_BUNDLE/Contents/Resources"
go build -ldflags "$LDFLAGS" -o "$ARM_BUNDLE/Contents/MacOS/MBD-Videoconverter" .
if [ -f "$FFMPEG_DARWIN_ARM64" ]; then
  cp "$FFMPEG_DARWIN_ARM64" "$ARM_BUNDLE/Contents/MacOS/ffmpeg"
else
  echo "  WARN: $FFMPEG_DARWIN_ARM64 not found, skipping bundled ffmpeg"
fi
cat > "$ARM_BUNDLE/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleExecutable</key><string>MBD-Videoconverter</string>
  <key>CFBundleIdentifier</key><string>$APPID</string>
  <key>CFBundleName</key><string>MBD-Videoconverter</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundlePackageType</key><string>APPL</string>
</dict></plist>
EOF
(cd "$OUTDIR/macos-arm64" && zip -ry "../MBD-Videoconverter-${VERSION}-macos-arm64.zip" "MBD-Videoconverter.app")

# ── macOS x64 + Windows via fyne-cross ───────────────────────────────────────
if command -v fyne-cross &>/dev/null && docker info &>/dev/null; then
  echo "Building macOS x64..."
  fyne_cross_version_inject
  fyne-cross darwin -arch amd64 -app-id "$APPID" -output MBD-Videoconverter
  fyne_cross_version_clean
  X64_BUNDLE="$OUTDIR/macos-x64/MBD-Videoconverter.app"
  rm -rf "$X64_BUNDLE"
  mkdir -p "$OUTDIR/macos-x64"
  cp -R "fyne-cross/dist/darwin-amd64/MBD-Videoconverter.app" "$X64_BUNDLE"
  if [ -f "$FFMPEG_DARWIN_X64" ]; then
    cp "$FFMPEG_DARWIN_X64" "$X64_BUNDLE/Contents/MacOS/ffmpeg"
  fi
  rm -rf fyne-cross/
  (cd "$OUTDIR/macos-x64" && zip -ry "../MBD-Videoconverter-${VERSION}-macos-x64.zip" "MBD-Videoconverter.app")

  echo "Building Windows amd64..."
  fyne_cross_version_inject
  fyne-cross windows -arch amd64 -app-id "$APPID" -output MBD-Videoconverter
  fyne_cross_version_clean
  WIN_DIR="$OUTDIR/windows-amd64"
  rm -rf "$WIN_DIR" && mkdir -p "$WIN_DIR"
  # fyne-cross packages Windows output as a zip; extract the .exe from it
  unzip -o -j "fyne-cross/dist/windows-amd64/MBD-Videoconverter.zip" "*.exe" -d "$WIN_DIR/"
  if [ -f "$FFMPEG_WIN_AMD64" ]; then
    cp "$FFMPEG_WIN_AMD64" "$WIN_DIR/ffmpeg.exe"
  fi
  rm -rf fyne-cross/
  (cd "$OUTDIR" && zip -r "MBD-Videoconverter-${VERSION}-windows-amd64.zip" "windows-amd64")
else
  echo "fyne-cross or Docker missing — skipping macOS x64 and Windows builds."
fi

echo "Done. Artifacts in $OUTDIR/"
