#!/usr/bin/env bash
# Build MBD-Videoconverter for macOS arm64, macOS x64, Windows amd64.
#
# Usage:
#   ./build.sh                Build only.
#   ./build.sh --release      Build, then commit the bumped VERSION,
#                             tag it, push, and create a GitHub release
#                             with the three ZIPs as assets.
#                             Requires: gh CLI, gh auth, clean working
#                             tree (other than VERSION), and that all
#                             three target ZIPs were produced.
#   ./build.sh --prerelease   Like --release but marks the GitHub
#                             release as a pre-release.
#
# Requires:
#   macOS arm64:  Go 1.21+, Xcode CLT
#   macOS x64 + Windows: Docker + fyne-cross
#     go install github.com/fyne-io/fyne-cross@latest
#     go install fyne.io/fyne/v2/cmd/fyne@latest

set -euo pipefail
export PATH="$HOME/go/bin:$PATH"

# ── Argument parsing ─────────────────────────────────────────────────────────
RELEASE=0
PRERELEASE=0
for arg in "$@"; do
  case "$arg" in
    --release)    RELEASE=1 ;;
    --prerelease) RELEASE=1; PRERELEASE=1 ;;
    -h|--help)
      sed -n '2,15p' "$0"
      exit 0
      ;;
    *)
      echo "Unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

# ── Pre-flight checks for release mode ───────────────────────────────────────
if [ "$RELEASE" = 1 ]; then
  if ! command -v gh &>/dev/null; then
    echo "❌ gh CLI not found. Install via 'brew install gh'." >&2
    exit 1
  fi
  if ! gh auth status &>/dev/null; then
    echo "❌ gh CLI not authenticated. Run 'gh auth login'." >&2
    exit 1
  fi
  # Working tree must be clean except for VERSION (which build.sh will modify).
  DIRTY=$(git status --porcelain | grep -Ev '^( M| ??)? *VERSION$' || true)
  if [ -n "$DIRTY" ]; then
    echo "❌ Working tree has uncommitted changes other than VERSION:" >&2
    echo "$DIRTY" >&2
    echo "   Commit or stash them before running --release." >&2
    exit 1
  fi
fi

# Clean up any generated version file on exit (covers normal exit and errors)
trap 'rm -f internal/version/version_gen.go' EXIT

# ── Version bump (auto-increment patch) ──────────────────────────────────────
VFILE=VERSION
CURRENT=$(cat "$VFILE")
MAJORMINOR=${CURRENT%.*}
PATCH=${CURRENT##*.}
NEXT="${MAJORMINOR}.$((PATCH + 1))"
echo "$NEXT" > "$VFILE"
VERSION=$NEXT
echo "Version: $VERSION"

LDFLAGS="-s -w -X github.com/webfraggle/mbd-video-converter/internal/version.Version=$VERSION"
APPID="de.modellbahn-displays.mbd-videoconverter"
OUTDIR="dist"
mkdir -p "$OUTDIR"

# fyne-cross splits -ldflags on spaces (strings.Fields), which breaks -X importpath=value.
# Work around: write a generated Go file with the version baked in, use it for fyne-cross
# builds (which run inside Docker / local fyne tool), then remove it afterwards.
VERSION_GEN="internal/version/version_gen.go"
fyne_cross_version_inject() {
  cat > "$VERSION_GEN" <<GOEOF
// Code generated by build.sh — DO NOT EDIT.
package version

func init() { Version = "$VERSION" }
GOEOF
}
fyne_cross_version_clean() {
  rm -f "$VERSION_GEN"
}

# ── Locate ffmpeg per platform ───────────────────────────────────────────────
# Drop static builds in ./build-deps/ (gitignored). Sources:
#   macOS arm64/x64:  https://evermeet.cx/ffmpeg/getrelease/zip   (signed + notarized)
#   Windows amd64:    https://github.com/BtbN/FFmpeg-Builds/releases  (use the LGPL build)
# Override any path via env var on the command line.
FFMPEG_DARWIN_ARM64="${FFMPEG_DARWIN_ARM64:-./build-deps/ffmpeg-darwin-arm64}"
FFMPEG_DARWIN_X64="${FFMPEG_DARWIN_X64:-./build-deps/ffmpeg-darwin-x64}"
FFMPEG_WIN_AMD64="${FFMPEG_WIN_AMD64:-./build-deps/ffmpeg.exe}"

# ── Generate Icon.icns from Icon.png (cached in build-deps) ──────────────────
ICON_PNG="Icon.png"
ICNS_FILE="build-deps/Icon.icns"
if [ -f "$ICON_PNG" ] && [ ! -f "$ICNS_FILE" ] && command -v iconutil &>/dev/null; then
  echo "Generating $ICNS_FILE from $ICON_PNG..."
  ICONSET_DIR="build-deps/Icon.iconset"
  rm -rf "$ICONSET_DIR" && mkdir -p "$ICONSET_DIR"
  for size in 16 32 64 128 256 512; do
    sips -z "$size" "$size" "$ICON_PNG" --out "$ICONSET_DIR/icon_${size}x${size}.png" >/dev/null
    sips -z "$((size*2))" "$((size*2))" "$ICON_PNG" --out "$ICONSET_DIR/icon_${size}x${size}@2x.png" >/dev/null
  done
  mkdir -p build-deps
  iconutil -c icns -o "$ICNS_FILE" "$ICONSET_DIR"
  rm -rf "$ICONSET_DIR"
fi

# ── macOS arm64 (native) ─────────────────────────────────────────────────────
echo "Building macOS arm64..."
ARM_BUNDLE="$OUTDIR/macos-arm64/MBD-Videoconverter.app"
rm -rf "$ARM_BUNDLE"
mkdir -p "$ARM_BUNDLE/Contents/MacOS" "$ARM_BUNDLE/Contents/Resources"
go build -ldflags "$LDFLAGS" -o "$ARM_BUNDLE/Contents/MacOS/MBD-Videoconverter" .
if [ -f "$FFMPEG_DARWIN_ARM64" ]; then
  cp "$FFMPEG_DARWIN_ARM64" "$ARM_BUNDLE/Contents/MacOS/ffmpeg"
else
  echo "  WARN: $FFMPEG_DARWIN_ARM64 not found, skipping bundled ffmpeg"
fi
ICON_PLIST_KEY=""
if [ -f "$ICNS_FILE" ]; then
  cp "$ICNS_FILE" "$ARM_BUNDLE/Contents/Resources/Icon.icns"
  ICON_PLIST_KEY='  <key>CFBundleIconFile</key><string>Icon</string>'
fi
cat > "$ARM_BUNDLE/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>CFBundleExecutable</key><string>MBD-Videoconverter</string>
  <key>CFBundleIdentifier</key><string>$APPID</string>
  <key>CFBundleName</key><string>MBD-Videoconverter</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundlePackageType</key><string>APPL</string>
$ICON_PLIST_KEY
</dict></plist>
EOF
(cd "$OUTDIR/macos-arm64" && zip -ry "../MBD-Videoconverter-${VERSION}-macos-arm64.zip" "MBD-Videoconverter.app")

# ── macOS x64 + Windows via fyne-cross ───────────────────────────────────────
if command -v fyne-cross &>/dev/null && docker info &>/dev/null; then
  ICON_FLAG=""
  if [ -f "$ICON_PNG" ]; then
    ICON_FLAG="-icon $ICON_PNG"
  fi

  echo "Building macOS x64..."
  fyne_cross_version_inject
  fyne-cross darwin -arch amd64 -app-id "$APPID" $ICON_FLAG -output MBD-Videoconverter
  fyne_cross_version_clean
  X64_BUNDLE="$OUTDIR/macos-x64/MBD-Videoconverter.app"
  rm -rf "$X64_BUNDLE"
  mkdir -p "$OUTDIR/macos-x64"
  cp -R "fyne-cross/dist/darwin-amd64/MBD-Videoconverter.app" "$X64_BUNDLE"
  if [ -f "$FFMPEG_DARWIN_X64" ]; then
    cp "$FFMPEG_DARWIN_X64" "$X64_BUNDLE/Contents/MacOS/ffmpeg"
  fi
  rm -rf fyne-cross/
  (cd "$OUTDIR/macos-x64" && zip -ry "../MBD-Videoconverter-${VERSION}-macos-x64.zip" "MBD-Videoconverter.app")

  echo "Building Windows amd64..."
  fyne_cross_version_inject
  fyne-cross windows -arch amd64 -app-id "$APPID" $ICON_FLAG -output MBD-Videoconverter
  fyne_cross_version_clean
  WIN_DIR="$OUTDIR/windows-amd64"
  rm -rf "$WIN_DIR" && mkdir -p "$WIN_DIR"
  # fyne-cross packages Windows output as a zip; extract the .exe from it
  unzip -o -j "fyne-cross/dist/windows-amd64/MBD-Videoconverter.zip" "*.exe" -d "$WIN_DIR/"
  if [ -f "$FFMPEG_WIN_AMD64" ]; then
    cp "$FFMPEG_WIN_AMD64" "$WIN_DIR/ffmpeg.exe"
  fi
  rm -rf fyne-cross/
  (cd "$OUTDIR" && zip -r "MBD-Videoconverter-${VERSION}-windows-amd64.zip" "windows-amd64")
else
  echo "fyne-cross or Docker missing — skipping macOS x64 and Windows builds."
fi

echo "Done. Artifacts in $OUTDIR/"

# ── Release mode: commit VERSION, tag, push, create GitHub release ───────────
if [ "$RELEASE" = 1 ]; then
  echo ""
  echo "── Release: $VERSION ──"

  ARM_ZIP="$OUTDIR/MBD-Videoconverter-${VERSION}-macos-arm64.zip"
  X64_ZIP="$OUTDIR/MBD-Videoconverter-${VERSION}-macos-x64.zip"
  WIN_ZIP="$OUTDIR/MBD-Videoconverter-${VERSION}-windows-amd64.zip"

  for zip in "$ARM_ZIP" "$X64_ZIP" "$WIN_ZIP"; do
    if [ ! -f "$zip" ]; then
      echo "❌ Release aborted: artifact missing: $zip" >&2
      echo "   (Did fyne-cross or Docker fail? All three ZIPs are required.)" >&2
      exit 1
    fi
  done

  if git rev-parse "$VERSION" >/dev/null 2>&1; then
    echo "❌ Tag $VERSION already exists. Bump major/minor in VERSION manually or delete the tag." >&2
    exit 1
  fi

  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
  if [ -n "$LAST_TAG" ]; then
    NOTES=$(git log "${LAST_TAG}..HEAD" --pretty=format:'- %s' --reverse)
  else
    NOTES=$(git log --pretty=format:'- %s' --reverse | head -100)
  fi
  if [ -z "$NOTES" ]; then
    NOTES="Release $VERSION"
  fi

  echo "Committing VERSION bump and tagging $VERSION..."
  git add VERSION
  git commit -m "Release $VERSION"
  git tag -a "$VERSION" -m "Release $VERSION"

  echo "Pushing $BRANCH and tag to origin..."
  git push origin "$BRANCH"
  git push origin "$VERSION"

  # Regular releases get marked as "Latest" on GitHub so users always
  # land on them. Pre-releases are explicitly NOT marked Latest, so an
  # existing stable release stays the one shown by default.
  if [ "$PRERELEASE" = 1 ]; then
    RELEASE_FLAGS="--prerelease --latest=false"
  else
    RELEASE_FLAGS="--latest"
  fi

  echo "Creating GitHub release..."
  gh release create "$VERSION" \
    --title "$VERSION" \
    --notes "$NOTES" \
    $RELEASE_FLAGS \
    "$ARM_ZIP" "$X64_ZIP" "$WIN_ZIP"

  echo ""
  echo "✅ Released $VERSION"
fi
